# Generated by Django 4.2.23 on 2025-07-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_message_options_remove_message_chat_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_chat_for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
