# Generated by Django 4.2.23 on 2025-07-20 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('specialties', models.ManyToManyField(blank=True, related_name='doctors', to='doctors.specialty')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_login_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
