# Generated by Django 4.2.23 on 2025-07-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(blank=True, help_text='E.g., Mon-Fri, Mon,Wed,Fri, or All Weekends', max_length=100, null=True),
        ),
    ]
