# Generated by Django 4.2.23 on 2025-08-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, help_text="Doctor's private notes for the appointment.", null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to='doctors.doctorslot'),
        ),
    ]
